import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/common/Header";
import Footer from "@/components/common/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  "breaking-news": breakingNews,
  recent
}: Readonly<{
  children: React.ReactNode;
  "breaking-news"?: React.ReactNode;
  recent?: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <Header />
        <div className="flex min-h-screen items-center justify-center bg-zinc-50 font-sans dark:bg-black">
          <main className="flex min-h-screen w-full max-w-6xl flex-col items-center justify-between py-8 md:py-16  px-4 md:px-16 bg-white dark:bg-black sm:items-start">
            {breakingNews}
            {recent}
            {children}
          </main>
        </div>
        <Footer />  
      </body>
    </html>
  );
}
